# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SMTP_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import smtplib
import sys

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):

    emailAddress = ""
    password = ""

    sendTo = ""
    subject = ""
    emailText = ""
    port = 0
    host = ""
    providerIndex = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 1003)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.emailLbl = QtWidgets.QLabel(self.centralwidget)
        self.emailLbl.setGeometry(QtCore.QRect(10, 10, 261, 25))
        self.emailLbl.setObjectName("emailLbl")

        self.emailTxt = QtWidgets.QLineEdit(self.centralwidget)
        self.emailTxt.setEnabled(False)
        self.emailTxt.setGeometry(QtCore.QRect(10, 40, 331, 31))
        self.emailTxt.setObjectName("emailTxt")

        self.passwordLbl = QtWidgets.QLabel(self.centralwidget)
        self.passwordLbl.setGeometry(QtCore.QRect(420, 10, 261, 25))
        self.passwordLbl.setObjectName("passwordLbl")

        self.passwordTxt = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordTxt.setEnabled(False)
        self.passwordTxt.setGeometry(QtCore.QRect(420, 40, 331, 31))
        self.passwordTxt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordTxt.setObjectName("passwordTxt")

        self.providerLbl = QtWidgets.QLabel(self.centralwidget)
        self.providerLbl.setGeometry(QtCore.QRect(10, 90, 261, 25))
        self.providerLbl.setObjectName("providerLbl")

        self.providerBx = QtWidgets.QComboBox(self.centralwidget)
        self.providerBx.setGeometry(QtCore.QRect(10, 120, 331, 31))
        self.providerBx.setEditable(True)
        self.providerBx.setObjectName("providerBx")
        self.providerBx.addItem("")
        self.providerBx.setItemText(0, "")
        self.providerBx.addItem("")
        self.providerBx.addItem("")
        self.providerBx.addItem("")

        self.loginbtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginbtn.setEnabled(False)
        self.loginbtn.setGeometry(QtCore.QRect(420, 110, 150, 46))
        self.loginbtn.setObjectName("loginbtn")

        self.toLbl = QtWidgets.QLabel(self.centralwidget)
        self.toLbl.setGeometry(QtCore.QRect(10, 250, 89, 25))
        self.toLbl.setObjectName("toLbl")

        self.toTxt = QtWidgets.QLineEdit(self.centralwidget)
        self.toTxt.setEnabled(False)
        self.toTxt.setGeometry(QtCore.QRect(10, 280, 751, 31))
        self.toTxt.setObjectName("toTxt")

        self.subjectLbl = QtWidgets.QLabel(self.centralwidget)
        self.subjectLbl.setGeometry(QtCore.QRect(10, 320, 89, 25))
        self.subjectLbl.setObjectName("subjectLbl")

        self.subjectTxt = QtWidgets.QLineEdit(self.centralwidget)
        self.subjectTxt.setEnabled(False)
        self.subjectTxt.setGeometry(QtCore.QRect(10, 350, 751, 31))
        self.subjectTxt.setObjectName("subjectTxt")

        self.messageLbl = QtWidgets.QLabel(self.centralwidget)
        self.messageLbl.setGeometry(QtCore.QRect(10, 380, 171, 25))
        self.messageLbl.setObjectName("messageLbl")

        self.messageTxt = QtWidgets.QTextEdit(self.centralwidget)
        self.messageTxt.setEnabled(False)
        self.messageTxt.setGeometry(QtCore.QRect(10, 410, 761, 311))
        self.messageTxt.setObjectName("messageTxt")

        self.attachmentLbl = QtWidgets.QLabel(self.centralwidget)
        self.attachmentLbl.setGeometry(QtCore.QRect(10, 720, 131, 25))
        self.attachmentLbl.setWordWrap(True)
        self.attachmentLbl.setObjectName("attachmentLbl")

        self.sendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBtn.setEnabled(False)
        self.sendBtn.setGeometry(QtCore.QRect(10, 800, 761, 46))
        self.sendBtn.setObjectName("sendBtn")

        self.attachmentBtn = QtWidgets.QPushButton(self.centralwidget)
        self.attachmentBtn.setEnabled(False)
        self.attachmentBtn.setGeometry(QtCore.QRect(10, 750, 251, 46))
        self.attachmentBtn.setObjectName("attachmentBtn")

        self.portTxt = QtWidgets.QLineEdit(self.centralwidget)
        self.portTxt.setEnabled(False)
        self.portTxt.setGeometry(QtCore.QRect(430, 210, 331, 31))
        self.portTxt.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.portTxt.setObjectName("portTxt")

        self.hostTxt = QtWidgets.QLineEdit(self.centralwidget)
        self.hostTxt.setEnabled(False)
        self.hostTxt.setGeometry(QtCore.QRect(10, 210, 331, 31))
        self.hostTxt.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.hostTxt.setObjectName("hostTxt")

        self.hostLbl = QtWidgets.QLabel(self.centralwidget)
        self.hostLbl.setGeometry(QtCore.QRect(10, 180, 131, 25))
        self.hostLbl.setObjectName("hostLbl")

        self.portLbl = QtWidgets.QLabel(self.centralwidget)
        self.portLbl.setGeometry(QtCore.QRect(430, 180, 89, 25))
        self.portLbl.setObjectName("portLbl")

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.loginbtn.clicked.connect(lambda: self.getAccountInfo())
        self.providerBx.currentIndexChanged.connect(lambda: self.enableMailLines())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.emailLbl.setText(_translate("MainWindow", "Email Address:"))
        self.passwordLbl.setText(_translate("MainWindow", "Password:"))
        self.providerLbl.setText(_translate("MainWindow", "Email Provider/Server:"))
        self.providerBx.setItemText(1, _translate("MainWindow", "Server"))
        self.providerBx.setItemText(2, _translate("MainWindow", "Outlook"))
        self.providerBx.setItemText(3, _translate("MainWindow", "Gmail"))
        self.loginbtn.setText(_translate("MainWindow", "Login"))
        self.toLbl.setText(_translate("MainWindow", "To:"))
        self.subjectLbl.setText(_translate("MainWindow", "Subject:"))
        self.messageLbl.setText(_translate("MainWindow", "Email message:"))
        self.attachmentLbl.setText(_translate("MainWindow", "Attachments:"))
        self.sendBtn.setText(_translate("MainWindow", "SEND"))
        self.attachmentBtn.setText(_translate("MainWindow", "Add attachments"))
        self.hostLbl.setText(_translate("MainWindow", "Host Name:"))
        self.portLbl.setText(_translate("MainWindow", "Port:"))

    def getAccountInfo(self):
        Ui_MainWindow.emailAddress = self.emailTxt.text()
        Ui_MainWindow.password = self.passwordTxt.text()

        print("Email Address:", Ui_MainWindow.emailAddress)
        print("Password:", Ui_MainWindow.password)

    def getEmailInfo(self):
        Ui_MainWindow.sendTo = self.toTxt.text()
        Ui_MainWindow.subject = self.subjectTxt.text()
        Ui_MainWindow.emailText = self.messageTxt.toPlainText()

        print("To:", Ui_MainWindow.sendTo)
        print("Subject:", Ui_MainWindow.subject)
        print("Email Text:", Ui_MainWindow.emailText)

    def enableMailLines(self):
        Ui_MainWindow.providerIndex = self.providerBx.currentIndex()
        if Ui_MainWindow.providerIndex == 1:
            self.hostTxt.setEnabled(True)
            self.portTxt.setEnabled(True)
            self.toTxt.setEnabled(True)
            self.subjectTxt.setEnabled(True)
            self.messageTxt.setEnabled(True)
            self.sendBtn.setEnabled(True)
            self.emailTxt.setEnabled(False)
            self.passwordTxt.setEnabled(False)
            self.loginbtn.setEnabled(False)
            self.sendBtn.clicked.connect(lambda: self.server())

        elif Ui_MainWindow.providerIndex > 1:
            self.hostTxt.setEnabled(False)
            self.portTxt.setEnabled(False)
            self.emailTxt.setEnabled(True)
            self.passwordTxt.setEnabled(True)
            self.loginbtn.setEnabled(True)
            self.toTxt.setEnabled(False)
            self.subjectTxt.setEnabled(False)
            self.messageTxt.setEnabled(False)
            self.sendBtn.setEnabled(False)

    def server(self):
        Ui_MainWindow.port = int(self.portTxt.text())
        try:
            Ui_MainWindow.host = self.hostTxt.text()
            Ui_MainWindow.port = int(self.portTxt.text())
            server = smtplib.SMTP(f"{Ui_MainWindow.host}:{Ui_MainWindow.port}")
            Ui_MainWindow.to = self.toTxt.text()
            Ui_MainWindow.subject = self.subjectTxt.text()
            Ui_MainWindow.emailText = self.messageTxt.toPlainText()
            msg = f"To: {Ui_MainWindow.to}\nSubject: {Ui_MainWindow.subject}\n\n{Ui_MainWindow.emailText}"
            server.connect(Ui_MainWindow.host, Ui_MainWindow.port)
            server.sendmail("", "", msg)
            server.quit()
        except Exception:
            print("Host unreachable, please verify host name and port number.")


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
