# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Client_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1267, 856)
        Form.setStyleSheet("")
        self.hostLbl = QtWidgets.QLabel(Form)
        self.hostLbl.setGeometry(QtCore.QRect(20, 10, 89, 25))
        self.hostLbl.setObjectName("hostLbl")
        self.portLbl = QtWidgets.QLabel(Form)
        self.portLbl.setGeometry(QtCore.QRect(470, 10, 89, 25))
        self.portLbl.setObjectName("portLbl")
        self.logLbl = QtWidgets.QLabel(Form)
        self.logLbl.setGeometry(QtCore.QRect(660, 130, 291, 25))
        self.logLbl.setObjectName("logLbl")
        self.msgLbl = QtWidgets.QLabel(Form)
        self.msgLbl.setGeometry(QtCore.QRect(20, 130, 89, 25))
        self.msgLbl.setObjectName("msgLbl")
        self.hostTxt = QtWidgets.QLineEdit(Form)
        self.hostTxt.setGeometry(QtCore.QRect(20, 40, 331, 31))
        self.hostTxt.setObjectName("hostTxt")
        self.connectBtn = QtWidgets.QPushButton(Form)
        self.connectBtn.setGeometry(QtCore.QRect(20, 80, 150, 46))
        self.connectBtn.setObjectName("connectBtn")
        self.msgTxt = QtWidgets.QTextEdit(Form)
        self.msgTxt.setEnabled(False)
        self.msgTxt.setGeometry(QtCore.QRect(20, 160, 591, 611))
        self.msgTxt.setObjectName("msgTxt")
        self.sendBtn = QtWidgets.QPushButton(Form)
        self.sendBtn.setEnabled(False)
        self.sendBtn.setGeometry(QtCore.QRect(20, 780, 150, 46))
        self.sendBtn.setObjectName("sendBtn")
        self.nicknameBtn = QtWidgets.QPushButton(Form)
        self.nicknameBtn.setEnabled(False)
        self.nicknameBtn.setGeometry(QtCore.QRect(920, 80, 150, 46))
        self.nicknameBtn.setObjectName("nicknameBtn")
        self.nicknameLbl = QtWidgets.QLabel(Form)
        self.nicknameLbl.setGeometry(QtCore.QRect(910, 10, 111, 25))
        self.nicknameLbl.setObjectName("nicknameLbl")
        self.closeBtn = QtWidgets.QPushButton(Form)
        self.closeBtn.setEnabled(False)
        self.closeBtn.setGeometry(QtCore.QRect(660, 780, 150, 46))
        self.closeBtn.setObjectName("closeBtn")
        self.portTxt = QtWidgets.QLineEdit(Form)
        self.portTxt.setGeometry(QtCore.QRect(470, 40, 331, 31))
        self.portTxt.setObjectName("portTxt")
        self.nicknameTxt = QtWidgets.QLineEdit(Form)
        self.nicknameTxt.setEnabled(False)
        self.nicknameTxt.setGeometry(QtCore.QRect(920, 40, 331, 31))
        self.nicknameTxt.setObjectName("nicknameTxt")
        self.logTxt = QtWidgets.QTextEdit(Form)
        self.logTxt.setEnabled(False)
        self.logTxt.setGeometry(QtCore.QRect(660, 160, 591, 611))
        self.logTxt.setReadOnly(True)
        self.logTxt.setObjectName("logTxt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hostLbl.setText(_translate("Form", "Host IP:"))
        self.portLbl.setText(_translate("Form", "Port:"))
        self.logLbl.setText(_translate("Form", "Message Log:"))
        self.msgLbl.setText(_translate("Form", "Message:"))
        self.connectBtn.setText(_translate("Form", "Connect"))
        self.sendBtn.setText(_translate("Form", "Send Message"))
        self.nicknameBtn.setText(_translate("Form", "Set Nickname"))
        self.nicknameLbl.setText(_translate("Form", "Nickname:"))
        self.closeBtn.setText(_translate("Form", "Close Client"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
